services:
  postgres:
    image: postgres:14
    container_name: notes_db
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: go_password
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"